### Login
POST http://localhost:5000/users/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

### Create a new user
POST http://localhost:5000/users/register
Content-Type: application/json

{
  "username": "aNewUser2",
  "password": "blablabla"
}

### Create a new article
POST http://localhost:5000/articles
Content-Type: application/json

{
  "nom": "tabouret"
}

### Créer tournée et ses crèches associées
POST http://localhost:5000/tournees/
Content-Type: application/json

{
  "nom": "Tournée manèges",
  "crèches": [
    {
      "nom": "Crèche 1",
      "articles": {
        "Langes S": 3,
        "Langes M": 2
      }
    },
    {
      "nom": "Crèche 2",
      "articles": {
        "Langes S": 1,
        "Langes M": 4
      }
    }
  ]
}

### Modifier une commande (crèche)
POST http://localhost:5000/creches/Rêverie
Content-Type: application/json

{
  "articles": {
    "Langes S": 3,
    "Inserts": 24
  }
}


