### Login
POST http://localhost:5000/users/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

### Create a new user
POST http://localhost:5000/users/register
Content-Type: application/json

{
  "username": "aNewUser2",
  "password": "blablabla"
}

### Create a new article
POST http://localhost:5000/articles/
Content-Type: application/json

{
  "nom": "tabouret2"
}

### Créer tournée et ses crèches associées
POST http://localhost:5000/tournees/
Content-Type: application/json

{
  "nom": "Tournée manèges555",
  "crèches": [
    {
      "nom": "Crèche 1",
      "articles": {
        "Langes S": 3,
        "Langes M": 2
      }
    },
    {
      "nom": "Crèche 2",
      "articles": {
        "Langes S": 1,
        "Langes M": 4
      }
    }
  ]
}

### Supprimer tournée
DELETE http://localhost:5000/tournees/Tournée manèges555

### Modifier une commande (crèche)
POST http://localhost:5000/creches/Rêverie
Content-Type: application/json

{
  "articles": {
    "Langes S": 3,
    "Inserts": 24
  }
}

### READ une crèche (crèche)
GET http://localhost:5000/creches/Rêverie

### Modifier le statut d'une commande
POST http://localhost:5000/creches/changerstatut/Rêverie
Content-Type: application/json

{
  "statut": "pas livré"
}


